### PR TITLE
Added all necessary changes for this to be a node module

### PR DESCRIPTION
**Pull request by austinbv**
I kept tests green and made all the little changes around making timecop a node module.  All it has to do is be published.

I also added code so when the version is changed in rake it version bumps in package.json as well.
I hope you enjoy.

Austin

### CODE REVIEW

**Comment by austinbv** [comment]
This fixes Issue #5

**Comment by jamesarosen** [comment]
I'm definitely looking forward to having node support.

I had some changes locally that I had neglected to push. They're on my master branch now. Can you rebase from that so I can merge cleanly?

**Comment by austinbv** [comment]
I fucked up the git history if you don't mind take from here or I can redo it

**Comment by jamesarosen** [comment]
If you don't mind, please give it another go.

**Comment by austinbv** [comment]
I figured I will do it asap

**Pull request closed without merging**
