### PR TITLE
Add Date.now() to MockDate.

### PR DESCRIPTION
**Pull request by jwark**
As per issue: https://github.com/jamesarosen/Timecop.js/issues/21

### CODE REVIEW

**Comment by jamesarosen** [comment]
This looks great. Could you undo the change to `timecop-0.1.1.js`? I'll produce a new release (0.2.0) after I merge this.

**Comment by jamesarosen** [comment]
I've made some changes to the `Rakefile` that should help with this. Running `rake` or `rake jshint` or `rake test` will no longer compile the distribution file.

**Comment by jwark** [comment]
I've undone the timecop-0.1.1.js change.  let me know if you need anything else.

**Comment by jamesarosen** [comment]
This is perfect :)

**Comment by cyril-sf** [comment]
@jamesarosen any chance you could release a new release for bower? Thanks.

**Pull request merged**
